### ISSUE TITLE
Travis setup is broken

### ISSUE THREAD

**Issue by simonlindholm** [indaplusplus/DefinitelyAUniqueChessImplementation#7]
(similar to https://github.com/indaplusplus/ajafer-chess/issues/2 )

Note the execution log here: https://travis-ci.org/indaplusplus/DefinitelyAUniqueChessImplementation/builds/280048323

It's suspiciously short, makes no note of tests, and includes the line:

```
[WARNING] JAR will be empty - no content was marked for inclusion!
```

Seems like `mvn clean verify` "works", but just outputs an empty jar file. Probably needs some config, or different organization of source files.

(Would be good practice to submit a failing test as a Pull Request, to see that Travis really tests what you think it tests!)

**Comment by paulvinell** [comment]
Couldn't get Maven to work with my structure (but I should have just stuck to Maven standards to begin with). I did some restructuring and now it works.

p.s. I forgot to tag the issues in my commits.

**Comment by simonlindholm** [comment]
Great!

> p.s. I forgot to tag the issues in my commits.

Do the next best thing and note the commit id in the issue. *Possibly* force-push with updated commit message, or push a revert + new commit with updated message, but that's not really worth it in this case.

Also, no need to use a "fixed" label, that was just for week 1 homework tracking - you can just close the issue.
